[versions]
lombok = "1.18.34"
junit = "5.11.3"
mssqlJdbc = "13.4.0.jre11"
hikaricp = "5.1.0"
slf4j = "2.0.16"
googleJavaFormat = "1.24.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mssql-jdbc = { module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "mssqlJdbc" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
google-java-format = { module = "com.google.googlejavaformat:google-java-format", version.ref = "googleJavaFormat" }
